### ISSUE TITLE
Unable to run the loan broker example on a K8 cluster

### ISSUE THREAD

**Issue by andrewrutter** [fabric8io/kubeflix#165]
I am trying to run the loanbroker sample but the services are failing to start. An example from the credit bureau is below. Please help been trying to stand this up as an example on using kubeflix over the naive Spring cloud approach but cannot get past this one.

Thanks,
Andrew

```
[INFO] F8:[NEW] loanbroker-credit-bureau-945504598-xd7wj status: Running 
[INFO] F8:[NEW] Tailing log of pod: loanbroker-credit-bureau-945504598-xd7wj
[INFO] F8:[NEW] Press Ctrl-C to scale down the app and stop tailing the log
[INFO] F8:[NEW] 
[INFO] F8: 16:14:56.414 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from Kubernetes config...
[INFO] F8: 16:14:56.448 [main] DEBUG io.fabric8.kubernetes.client.Config - Did not find Kubernetes config at: [/root/.kube/config]. Ignoring.
[INFO] F8: 16:14:56.449 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from service account...
[INFO] F8: 16:14:56.449 [main] DEBUG io.fabric8.kubernetes.client.Config - Found service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt].
[INFO] F8: 16:14:56.466 [main] DEBUG io.fabric8.kubernetes.client.Config - Found service account token at: [/var/run/secrets/kubernetes.io/serviceaccount/token].
[INFO] F8: 16:14:56.466 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client namespace from Kubernetes service account namespace path...
[INFO] F8: 16:14:56.467 [main] DEBUG io.fabric8.kubernetes.client.Config - Found service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace].
[INFO] F8: 2016-12-23 16:14:59.116  WARN [bootstrap,,,] 1 --- [           main] i.f.s.cloud.kubernetes.StandardPodUtils  : Failed to get pod with name:[loanbroker-credit-bureau-945504598-xd7wj]. You should look into this if things aren't working as you expect. Are you missing serviceaccount permissions?
[INFO] F8: 
[INFO] F8: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
[INFO] F8:      at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57) ~[kubernetes-client-1.4.14.jar!/:na]
[INFO] F8:      at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:172) ~[kubernetes-client-1.4.14.jar!/:na]
[INFO] F8:      at io.fabric8.spring.cloud.kubernetes.StandardPodUtils.internalGetPod(StandardPodUtils.java:56) [spring-cloud-kubernetes-core-0.1.3.jar!/:na]
[INFO] F8:      at io.fabric8.spring.cloud.kubernetes.StandardPodUtils.lambda$new$0(StandardPodUtils.java:40) [spring-cloud-kubernetes-core-0.1.3.jar!/:na]
[INFO] F8:      at io.fabric8.spring.cloud.kubernetes.StandardPodUtils$$Lambda$1/186276003.get(Unknown Source) [spring-cloud-kubernetes-core-0.1.3.jar!/:na]
[INFO] F8:      at io.fabric8.spring.cloud.kubernetes.LazilyInstantiate.swapper(LazilyInstantiate.java:41) [spring-cloud-kubernetes-core-0.1.3.jar!/:na]
[INFO] F8:      at io.fabric8.spring.cloud.kubernetes.LazilyInstantiate.lambda$new$0(LazilyInstantiate.java:34) [spring-cloud-kubernetes-core-0.1.3.jar!/:na]
[INFO] F8:      at io.fabric8.spring.cloud.kubernetes.LazilyInstantiate$$Lambda$2/1685538367.get(Unknown Source) [spring-cloud-kubernetes-core-0.1.3.jar!/:na]
[INFO] F8:      at io.fabric8.spring.cloud.kubernetes.LazilyInstantiate.get(LazilyInstantiate.java:29) [spring-cloud-kubernetes-core-0.1.3.jar!/:na]
[INFO] F8:      at io.fabric8.spring.cloud.kubernetes.profile.KubernetesProfileApplicationListener.addKubernetesProfile(KubernetesProfileApplicationListener.java:49) [spring-cloud-kubernetes-core-0.1.3.jar!/:na]
[INFO] F8:      at io.fabric8.spring.cloud.kubernetes.profile.KubernetesApplicationContextInitializer.initialize(KubernetesApplicationContextInitializer.java:53) [spring-cloud-kubernetes-core-0.1.3.jar!/:na]
[INFO] F8:      at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:635) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
[INFO] F8:      at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:349) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
[INFO] F8:      at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
[INFO] F8:      at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
[INFO] F8:      at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:140) [spring-cloud-context-1.1.1.RELEASE.jar!/:1.1.1.RELEASE]
[INFO] F8:      at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:84) [spring-cloud-context-1.1.1.RELEASE.jar!/:1.1.1.RELEASE]
[INFO] F8:      at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:62) [spring-cloud-context-1.1.1.RELEASE.jar!/:1.1.1.RELEASE]
[INFO] F8:      at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166) [spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
[INFO] F8:      at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138) [spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
[INFO] F8:      at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121) [spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
[INFO] F8:      at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
[INFO] F8:      at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
[INFO] F8:      at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:337) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
[INFO] F8:      at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
[INFO] F8:      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
[INFO] F8:      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
[INFO] F8:      at io.fabric8.kubeflix.examples.loanbroker.creditbureau.Application.main(Application.java:30) [classes!/:na]
[INFO] F8:      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40-internal]
[INFO] F8:      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40-internal]
[INFO] F8:      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40-internal]
[INFO] F8:      at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40-internal]
[INFO] F8:      at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [loanbroker-credit-bureau-1.0-SNAPSHOT.jar:na]
[INFO] F8:      at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [loanbroker-credit-bureau-1.0-SNAPSHOT.jar:na]
[INFO] F8:      at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [loanbroker-credit-bureau-1.0-SNAPSHOT.jar:na]
[INFO] F8:      at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [loanbroker-credit-bureau-1.0-SNAPSHOT.jar:na]
[INFO] F8: Caused by: java.net.UnknownHostException: kubernetes.default.svc: unknown error
[INFO] F8:      at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_40-internal]
[INFO] F8:      at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:907) ~[na:1.8.0_40-internal]
[INFO] F8:      at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302) ~[na:1.8.0_40-internal]
[INFO] F8:      at java.net.InetAddress.getAllByName0(InetAddress.java:1255) ~[na:1.8.0_40-internal]
[INFO] F8:      at java.net.InetAddress.getAllByName(InetAddress.java:1171) ~[na:1.8.0_40-internal]
[INFO] F8:      at java.net.InetAddress.getAllByName(InetAddress.java:1105) ~[na:1.8.0_40-internal]
[INFO] F8:      at okhttp3.Dns$1.lookup(Dns.java:39) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:172) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:138) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:80) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:178) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at io.fabric8.kubernetes.client.utils.HttpClientUtils$3.intercept(HttpClientUtils.java:102) ~[kubernetes-client-1.4.14.jar!/:na]
[INFO] F8:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at okhttp3.RealCall.execute(RealCall.java:60) ~[okhttp-3.4.1.jar!/:na]
[INFO] F8:      at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:234) ~[kubernetes-client-1.4.14.jar!/:na]
[INFO] F8:      at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:229) ~[kubernetes-client-1.4.14.jar!/:na]
[INFO] F8:      at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:225) ~[kubernetes-client-1.4.14.jar!/:na]
[INFO] F8:      at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:590) ~[kubernetes-client-1.4.14.jar!/:na]
[INFO] F8:      at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:165) ~[kubernetes-client-1.4.14.jar!/:na]
[INFO] F8:      ... 34 common frames omitted
[INFO] F8: 
[INFO] F8: 2016-12-23 16:14:59.409  INFO [bootstrap,,,] 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@2f410acf: startup date [Fri Dec 23 16:14:59 UTC 2016]; root of context hierarchy
[INFO] F8: 2016-12-23 16:15:00.503  INFO [bootstrap,,,] 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$4813c385] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

**Comment by iocanel** [comment]
@andrewrutter: what is the service account your pods are using?
