### ISSUE TITLE
turbine discovery question

### ISSUE THREAD

**Issue by mliu5715k** [fabric8io/kubeflix#65]
has anyone been able to get the turbine discovery working out side the fabric8 sandbox?

**Comment by jimmidyson** [comment]
One for you @iocanel?

**Comment by mliu5715k** [comment]
so everything seems to match except this error from "kubectl logs turbine-q6uop"

```
Apr 05, 2016 10:17:28 PM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=34989] throws
java.io.IOException: The server sockets created using the LocalRMIServerSocketFactory only accept connections from clients running on the host where the RMI remote objects have been exported.
	at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(LocalRMIServerSocketFactory.java:114)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:400)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:372)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by iocanel** [comment]
@mliu5715k: Turbine not finding streams usually means that either there is a label mismatch in the pods or the service account on the turbine server is not correct (needs to be able to query endpoints).

For purely troubleshooting purposes the turbine server exposes /discovery which should display the discovered streams or a meaningful exception.

**Comment by mliu5715k** [comment]
@iocanel: thank you, but some clarification would be very helpful.
- you mentioned label matching, besides using the two labels with correct values, there is really nothing to match as "using the same values in other pods/svs"?
```
bucky:openshift mliu5715k$ kubectl describe rc hello-hystrix
Name:		hello-hystrix
Namespace:	laroc
Image(s):	laroc/hello-hystrix:1.0.14
Selector:	hystrix.cluster=default,hystrix.enabled=true,project=hello-hystrix
Labels:		hystrix.cluster=default,hystrix.enabled=true,project=hello-hystrix
Replicas:	2 current / 2 desired
Pods Status:	2 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
No events.
```
- service account on turbine, do you mean how the turbine service object is defined in k8?
```
kubectl describe svc turbine
Name:			turbine
Namespace:		laroc
Labels:			project=turbine
Selector:		project=turbine
Type:			ClusterIP
IP:			192.168.1.80
Port:			<unnamed>	80/TCP
Endpoints:		192.168.45.2:8080
Session Affinity:	None
No events.
```
yes i can curl the cluster ip AND the endpoint
```
curl http://192.168.1.80/turbine.stream
: ping
data: {"reportingHostsLast10Seconds":0,"name":"meta","type":"meta","timestamp":1459958173750}
```

**Comment by iocanel** [comment]
Yes, all pods that expose hysterix stream need the 2 hystrix lables, with the exact values.

Well the svc itself doesn't say much. It needs to be associated with an scc that allows access to the api server. But lets leave that for now....

Can you try a 
curl http://192.168.1.80/discovery

and let me know of the output?

**Comment by iocanel** [comment]
@mliu5715k: see my comment above.

**Comment by mliu5715k** [comment]
@iocanel:
```
[root@hystrix-dashboard-m2nd7 /]# curl http://192.168.1.80/discovery
<h1>Hystrix Endpoints:</h1>
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:385)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:57)
	at io.fabric8.kubeflix.discovery.KubernetesDiscovery.getInstanceList(KubernetesDiscovery.java:65)
	at io.fabric8.kubeflix.DiscoveryFeedbackServlet.doGet(DiscoveryFeedbackServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:816)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: kubernetes.default.svc
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at com.squareup.okhttp.Dns$1.lookup(Dns.java:39)
	at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
	at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:210)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:383)
	... 29 more
```

**Comment by jimmidyson** [comment]
> java.net.UnknownHostException: kubernetes.default.svc

Indicates that DNS isn't configured properly in your cluster. Are you running the DNS addon for Kubernetes (I assume you're running vanilla kubernetes, not openshift)?

**Comment by mliu5715k** [comment]
NOPE! 
Can I get around that by using the ENV variables?

**Comment by jimmidyson** [comment]
Of course you can (I think) :)

KUBERNETES_MASTER should contain the full address to the master. e.g. `https://your.master.com:8443`

But there may be other problems that you hit by not running DNS - that should really be a prerequisite for any kube cluster now IMO.

**Comment by mliu5715k** [comment]
have to discuss that with our admin who has a thing against k8 DNS.

**Comment by mliu5715k** [comment]
@jimmidyson: passing the ENV variable worked. Thanks!

**Comment by jimmidyson** [comment]
Ah cool! Thanks for letting us know.
