### ISSUE TITLE
kubeflix not working with kubernetes 1.2

### ISSUE THREAD

**Issue by raffaelespazzoli** [fabric8io/kubeflix#82]
Hi,

I'm working with OpenShift 3.1 which aligns with kubernetes 1.1.
It looks like the new spring based framework requires configmaps to be available.
I'd like to request configmaps to be optionals and that the application starts even if they are not available

Thanks
Raffaele

**Comment by iocanel** [comment]
@raffaelespazzoli: definitely!

Can you please provide some more details on the error you are having? A stack trace maybe?

**Comment by raffaelespazzoli** [comment]
here is the stacktrace that I see, after which the pod dies:

please notice that the error message says that my service account doesn't have access, but that is not totally accurate, the service account I'm using has cluster-read access. I know that because I was getting the same error when spring was trying to inspect the pod and I was able to grant it access and then I started seeing this error:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 1 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc.cluster.local/api/v1/configmaps/turbine-server. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:290)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:241)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:212)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:205)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:510)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:118)
	at io.fabric8.spring.cloud.kubernetes.config.ConfigMapPropertySource.getData(ConfigMapPropertySource.java:60)
	at io.fabric8.spring.cloud.kubernetes.config.ConfigMapPropertySource.<init>(ConfigMapPropertySource.java:48)
	at io.fabric8.spring.cloud.kubernetes.config.ConfigMapPropertySourceLocator.locate(ConfigMapPropertySourceLocator.java:48)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:85)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:640)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
	at io.fabric8.kubeflix.TurbineServerApplication.main(TurbineServerApplication.java:32)
```

**Comment by iocanel** [comment]
It should be fine now
